---
  title: "Problem Sets"
  output: 
    html_document:
      toc: true
      toc_depth: 3
      toc_float: true
      self_contained: true
      df_print: paged
      mathjax: default
  bibliography: eco204_books.bib  
  link-citations: yes
  linkcolor: blue
---
  
Please submit the problem set in **PDF** format within the **specified deadline** in google classroom. If you use Excel or R to solve the problem set, please submit the **Excel file** or **R Script** file as well.

## Problem Set 1

- **Deadline**: 5th July, 10:00 PM, 2025
- Question [PS1 Question](problem_sets/ps_1/PS_1.pdf), Data [PS1 Data](problem_sets/ps_1/data/Student_Lunch.xlsx)
- Solution [PS1 Solution (Excel File - Solved by Habiba)](problem_sets/ps_1/solutions/PS_1_soln.xlsx)

## Problem Set 2

- **Deadline**: 16th July, 10:00 PM, 2025
- Question [PS2 Question](problem_sets/ps_2/PS_2.pdf), Data [PS2 Data](problem_sets/ps_2/data_file/Student_Satisfaction.xlsx)
- Solution 
  - [PS2 Partial Solution (Excel File - Solved by Habiba)](problem_sets/ps_2/solutions/PS_2_soln.xlsx)
  - [PS2 Partial PDF typed Solution](problem_sets/ps_2/solutions/PS_2_soln.pdf)

## Problem Set 3
- **Deadline**: 7th August, 10:00 PM, 2025
- Question [PS3 Question](problem_sets/ps_3/PS_3.pdf), Data [PS3 Data](problem_sets/ps_3/data_file/data_msales_aprice.xlsx)
-  Additional Question Included [PS3 - Additional Question](problem_sets/ps_3/PS_3_additional.pdf) - Please solve additional questions before Mid - 2
- Solution 

## Problem Set 4
- **Deadline**: 1st September, 10:00 PM, 2025
- Question [PS4 Question](problem_sets/ps_4/PS_4.pdf), Data [PS4 Data](problem_sets/ps_4/data/CoffeeChain.xlsx)
-  *Sample Works* - Please check the sample work for better understanding of the problem set requirements
   - [Data File](problem_sets/ps_4/sample_work/Showtime_New.xlsx)
   - [Sample Solution Html File](problem_sets/ps_4/sample_work/SamplePS_Solutions.html)
   - [Sample Solution PDF File](problem_sets/ps_4/sample_work/SamplePS_Solutions.pdf)
   - [Sample Solution R Script File](problem_sets/ps_4/sample_work/SamplePS_Solutions.R)
   - [Sample Solution R Markdown File](problem_sets/ps_4/sample_work/SamplePS_Solutions.Rmd)
  
- Solution 


<div style="height:10cm;"></div>
