---
  title: "Project Work"
  output: 
    html_document:
      toc: true
      toc_depth: 3
      toc_float: true
      self_contained: true
      df_print: paged
      mathjax: default
  bibliography: eco204_books.bib  
  link-citations: yes
  linkcolor: blue
---
  

Choose one dataset from the list below. For the dataset you select, complete all tasks written in the [Project Details](project_work/Project_Details.pdf) document. You have following two options,

  - **Doing Work using MS Excel + MS Word:** In this case you perform the regression using MS Excel, write the report in MS Word, and submit the Excel file and a PDF (produced from the Word, I will not accept the MS Word file) file.
  - Or, 
  - **Doing the work using R and LaTeX:** In this case you perform the regression using R, write the report in R Markdown, and submit the knitted HTML file (or PDF file) and the R Markdown file.

If you submit both a fully reproducible R Markdown report and a LaTeX write-up, you will receive a +3 bonus points on the final exam.

Datasets are allocated on a **first-come, first-served** basis. To reserve a dataset, email STH or Habiba Afroz or Write in Discord with your group members' name and the chosen dataset — **once a dataset is reserved for a group it cannot be used by others**. Groups may have **at most two members**. So please send me an email or write in Discord with the following information as soon as you can.

- Group Members' Names
- Dataset Name (e.g., earns, approval, etc.)


If you have questions about a dataset or need an exception, contact the Me or Habiba Afroz via email or Discord.  

## **Project Details**

Please see [Project Details](project_work/Project_Details.pdf) for the details of the project.

## **Datasets**

The datasets are taken from @wooldridge2016introductory

- [approval.xlsx](project_work/all_data_sets/approval.xlsx), [approval_info.txt](project_work/all_data_sets/approval_info.txt)

- [athlet2.xlsx](project_work/all_data_sets/athlet2.xlsx), [athlet2_info.txt](project_work/all_data_sets/athlet2_info.txt)

- [earns.xlsx](project_work/all_data_sets/earns.xlsx), [earns_info.txt](project_work/all_data_sets/earns_info.txt)

- [fertil3.xlsx](project_work/all_data_sets/fertil3.xlsx), [info file](project_work/all_data_sets/fertil3_info.txt)

- [intdef.xlsx](project_work/all_data_sets/intdef.xlsx), [intdef_info.txt](project_work/all_data_sets/intdef_info.txt)

- [inven.xlsx](project_work/all_data_sets/inven.xlsx), [inven_info.txt](project_work/all_data_sets/inven_info.txt)

- [happiness.xlsx](project_work/all_data_sets/happiness.xlsx), [happiness_info.txt](project_work/all_data_sets/happiness_info.txt)

- [prminwge](project_work/all_data_sets/prminwge.xlsx), [prminwge_info.txt](project_work/all_data_sets/prminwge_info.txt)

- [rdchem.xlsx](project_work/all_data_sets/rdchem.xlsx), [rdchem_info.txt](project_work/all_data_sets/rdchem_info.txt)

- [traffic1.xlsx](project_work/all_data_sets/traffic1.xlsx), [traffic1_info.txt](project_work/all_data_sets/traffic1_info.txt)




## **Formatting**

Formatting your project properly is very important, please see the instructional video on how to format your project properly.


<div style="height:2cm;"></div>

# **References**

<div id="refs"></div>

<div style="height:2cm;"></div>

