---
  title: "Sessions"
  output: 
    html_document:
      toc: true
      toc_depth: 3
      toc_float: true
      self_contained: true
      df_print: paged
      mathjax: default
  bibliography: causal_group_books.bib  
  link-citations: yes
  linkcolor: blue
---
  
Here are the list of papers / book chapters that we will read .... 

#  **Session 1** (Causal Effect and RCT)

We will start with the basics of Causal Effect and RCT, the primary reading is Chapter 1, 2 of @angrist_2009. The key questions we will try to understand are following 

- What do we mean by Causal Effect? 
- Why can't we directly calculate unit level causal effect? (Known as - *The Fundamental Problem of Causality*)?
- What is the *Average Treatment Effect*, *Average Treatment Effect on the Treated*, *Average Treatment Effect on the Untreated* (these are all **parameters**)?
- What is the *Identification Problem*?
- How RCT solves identification problem and why RCT is considered to be the *gold standard* of causal inference (also many may disagree, notably Nobel laureate Angus Deaton)?

<br>

# **Session 2** (Regression and Causality)


<br>

# **References**

<div id="refs"></div>
